name = "aims-console-sync"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "INCIDENTS"
id = "95a0e8af8d4649d39a14d8afdef4780e"

[vars]
CORS_ORIGIN = "https://aims-console.vercel.app"
